# Generated by Django 3.1.5 on 2021-02-06 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Cake', 'Cake'), ('Cupcakes', 'Cupcakes'), ('DS', 'Dessert Shots'), ('Cakesicles', 'Cakesicles')], max_length=50, null=True)),
                ('minprice', models.FloatField(null=True)),
                ('Maxprice', models.FloatField(null=True)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('Customisation', models.CharField(max_length=1000, null=True)),
                ('Price', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=50, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=4, primary_key=True, serialize=False)),
                ('customisation', models.CharField(max_length=1000, null=True)),
                ('price', models.FloatField(null=True)),
                ('paymethod', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=500, null=True)),
                ('date', models.DateField()),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
