# Generated by Django 3.1.5 on 2021-02-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='username',
        ),
    ]
