# Generated by Django 3.1.5 on 2021-02-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210214_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
