# Generated by Django 3.1.5 on 2021-02-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210214_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
