# Generated by Django 3.1.5 on 2021-02-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_request_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='product_id',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
