# Generated by Django 3.1.5 on 2021-02-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210219_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
