# Generated by Django 3.1.5 on 2021-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210219_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='paymethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=50, null=True),
        ),
    ]
