# Generated by Django 3.1.5 on 2021-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
