# Generated by Django 3.1.5 on 2021-02-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_request_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='name',
        ),
    ]
