# Generated by Django 3.1.5 on 2021-04-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210225_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
