# Generated by Django 3.1.5 on 2021-04-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
